### ISSUE TITLE
Doubt about FFT spectral analysis

### ISSUE THREAD

**Issue by DiDomenicoSimone** [LorenzoBianconi/ath_spectral#3]
Dear Lorenzo,
I think the "ath_spectral" project is a very useful tool to visualize and understand a radio channel in the frequency domain. 
That said, I have a doubt about the data that are extracted.
When you mention that the AR92xx and AR93xx have the ability to report FFT data including the
absolute magnitude of the wireless signal for each FFT bin, are you referring to the received signal (Y(k)) or directly to the channel frequency response (H(k))?.

Thanks a lot in advance.

Simone

**Comment by LorenzoBianconi** [comment]
Hi Simone,

ar9xxxx reports for each bin real + imaginary part of the frequency slot, I mean:
abs(real) + abs(img)
it is just an approximation of the amplitude of the bin. Taking into account noise floor we can calculate the received signal strength (RSSI)

Regards,
Lorenzo
